services:
  db:
    image: pgvector/pgvector:pg16
    env_file: ./docker/db.env
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: ["uvicorn", "server.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./server:/atlascope/server/
    environment:
      - DB_URL=postgresql://admin:adminpass@db:5432/atlascope
    ports:
      - 8000:8000
