name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel pytest isort
      - name: Style check
        run: |
          isort .
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pytest
          python -m pip install -r requirements.txt
      - name: Start containers
        working-directory: atlascope_prototype
        run: docker compose up -d
      - name: Init Girder
        working-directory: atlascope_prototype
        run: |
          docker compose exec girder python3 -c "import init;init.init_girder('admin', 'atlascope')"
      - name: Run Tests
        run: |
          python -m pytest TCGA/tests/test_examples.py
          python -m pytest TCGA/tests/test_process_feature_vectors.py
      - name: Stop containers
        if: always()
        working-directory: atlascope_prototype
        run: docker compose stop
